name: Native English Spain
favicon: null
layout_spectrum: 0.51274
typography_spectrum: 1
title: 'Making English Simple, Fun & Affordable!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a208c'
    - '#ffffff'
    - '#e92219'
    - '#686868'
    - '#f2797d'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
