typography_spectrum: 1
color:
  brandColors:
    - '#0a208c'
    - '#ffffff'
    - '#e92219'
    - '#686868'
    - '#f2797d'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.73779
analytics:
  google: null
  facebook: null
  twitter: null
author:
  url: 'http://nativeenglishspain.com'
  email: nativeenglish.es@gmail.com
  name: Native English Spain
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/33958e38-7b40-44d4-9946-39573391d200.png
name: Native English Spain
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About Us
    id: c158842a-b887-4663-bae1-c75deeb4154a
    type: content
  - name: Recommendations
    id: 51650b4f-ae65-41a4-807f-8653d12cb315
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bc858566-16c1-4509-af93-9ddc00141461.png
title: 'Making English Simple, Fun & Affordable!'
purpose: []
