name: Native English Spain
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: 'Making English Simple, Fun & Affordable!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e6edf0'
    - '#d08204'
    - '#b13e00'
    - '#898f2e'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
